/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AITutorModule: typeof import('./components/learning/AITutorModule.vue')['default']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    AResult: typeof import('ant-design-vue/es')['Result']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpace: typeof import('ant-design-vue/es')['Space']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    AuthModal: typeof import('./components/auth/AuthModal.vue')['default']
    BlurText: typeof import('./components/animations/BlurText.vue')['default']
    BuildingCard: typeof import('./components/BuildingCard.vue')['default']
    BuildingFilter: typeof import('./components/BuildingFilter.vue')['default']
    BuildingModal: typeof import('./components/ui/BuildingModal.vue')['default']
    DecryptedText: typeof import('./components/animations/DecryptedText.vue')['default']
    EyeModule: typeof import('./components/learning/EyeModule.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Iridescence: typeof import('./components/animations/Iridescence.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PuzzleGame: typeof import('./components/learning/PuzzleGame.vue')['default']
    PuzzleModule: typeof import('./components/learning/PuzzleModule.vue')['default']
    QuizModule: typeof import('./components/learning/QuizModule.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShinyText: typeof import('./components/animations/ShinyText.vue')['default']
    SpotlightCard: typeof import('./components/animations/SpotlightCard.vue')['default']
    ThemeLanguageSwitcher: typeof import('./components/ThemeLanguageSwitcher.vue')['default']
    TimelineItem: typeof import('./components/TimelineItem.vue')['default']
  }
}
